### ISSUE TITLE
Handling non-RR supported Gamepad types

### ISSUE THREAD

**Issue by mxpidd** [lelandpaul/ringingroom#213] opened 2021-02-17 10:00 UTC
Note: Not yet properly tested. Probably needs a gamepad index as a key. I'll look further. 

The mobile controller count includes Gamepad controllers other than eBell and ActionXL.
This may make the count wrong when testing to assign just one pair of controllers. 
I believe this is resolved, in the set_controllers function, by adding controller objects to controller_list using a push for eBells and ActionXL rather than adding templated objects based on objected in navigator.getGamepads().

                    if (curCont.id.includes('0ffe') && curCont.connected) {
                        contObj.type = "ActionXL";
                        this.controller_list.push(contObj)
                    } else if (curCont.id.includes('1234') && curCont.connected) {
                        contObj.type = "vJoy";
                    } else if (curCont.id.includes('2341') && curCont.connected) {
                        contObj.type = "eBell";
                        this.controller_list.push(contObj)
                    } else {
                    }

**Comment by mxpidd** [comment] 2021-02-17 15:58
Updated proposed solution, 

[ringing_room.zip](https://github.com/lelandpaul/ringingroom/files/5996897/ringing_room.zip)

I'm sure there are better implementations, but this works for me.

Be aware, I've not noticed it in documentation, but the gamepad API appears to be limited to 4 gamepads.

**Comment by lelandpaul** [comment] 2021-02-20 17:37
This looks good, Mike — my only quibble is that the final empty `else` block is unnecessary. I'll throw up a PR for it later — or you can if you get the chance before me.

**Comment by mxpidd** [comment] 2021-02-20 20:21
I've lacked clarity again. The zip file on the second comment contains something that, I believe, actually works. My initial naive suggestion worked only because of the order of the controllers in the gamepad api.

I'm yet to really get to grips with GitHub but will try with the PR,
but don't hold your breath and feel free to do it yourself.

Longer term, do you want to include settings to allow alternative controllers to be used or add to the supported controllers in response to demand?

**Comment by JessP-utaw** [comment] 2021-02-20 22:40
I'm probably coming late to this, but FWIW I've been playing with a PS4 controller mapped with DS4Windows this whole time, and (touch wood) it's worked great

**Comment by mxpidd** [comment] 2021-02-21 08:10
Jess, if you visit https://gamepad-tester.com/ and let me have the reported vendor  and product codes for the DS4Windows controller it can easily be included.

Leland, I think we need a policy decision whether whether to show everything that is found, as identified by the Gamepad API, whether or not it works or to restrict to those that we know do work, updating the code as necessary.

**Comment by JessP-utaw** [comment] 2021-02-21 11:41
I just map it to regular keypresses e.g. (x) -> [space]. I also use it to drive the mouse etc, so my main requirement is that native gamepad support wouldn't interfere with that (or would be able to be turned off).

Here's the readout from that site
Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)
![image](https://user-images.githubusercontent.com/71704094/108623920-906db980-7439-11eb-89a3-7ced7ba52f91.png)

**Comment by mxpidd** [comment] 2021-02-21 12:21
The gamepad input uses accelerometer data for strikes so shouldn't interfere,and use of the controller feature can be turned off.

If we only recognise controllers that we know work then you should have no issue. 

It would be good if you could check on the dev server. It might be that the current version might, by default, do something unexpected with button presses unless turned off because Gamepad buttons are mapped to shortcut keys.

**Comment by JessP-utaw** [comment] 2021-02-22 14:01
On dev it does interfere - I have (x) mapped to space, and x now also triggers a single. Also I have right-stick mapped to the mouse and it makes the bell ring.

Disabling it works fine though so I don't really have any problems, but it doesn't persist on refresh.

**Comment by JessP-utaw** [comment] 2021-02-22 14:02
Shaking and tilting the controller doesn't do anything

**Comment by mxpidd** [comment] 2021-02-22 16:26
Thanks Jess,

I've a fix which should sort the button issue waiting to go in.

To handle the refresh a user associated setting to initialise each session with controllers enabled/disabled, or just recall last setting, would sort this.

Leyland, do you think this appropriate?

Jess, it would be good if you could check out your controllers again if/as/when this hits the dev server.

**Comment by lelandpaul** [comment] 2021-03-02 23:06
Sorry — I've been out of town and am just catching up on this. Do I understand correctly that the issue is: Our current motion-controller setting prevents the use of gamepad controllers as non-motion-control input devices?

Having a user setting for this seems good, but I want to hold off until we have a more robust system for managing user preferences in place — this is in the works for the next major release, as we'll also need it for allowing custom hotkeys. Once that's in place, it should be relatively trivial to add something like this.

**Comment by mxpidd** [comment] 2021-03-03 07:39
The current system produces calls when buttons are pressed on gamepads for which motion-generated strikes have not been set up. 
Controllers would need to be turned off each time a tower page was entered to refreshed. See item 2 below. 

#214 Aims to address:
1. Controller count included controllers that aren't supported, whether motion or button driven.
This meant that the count doesn't match the number of controllers available for assignment. 
2. Recognition of controllers other than eBells or ActionXL.
Limiting recognition avoids anyone who has their own system to send keystrokes generated by a gamepad button press having to turn off controllers each time. Otherwise, assuming two gamepads have been auto-assigned to bells, their own system sends a keystroke but the button press is recognised and also produces an unwanted call. 
I believe the limit to recognised controllers should be relaxed once settings are recalled, perhaps giving option to opt in to recognition of other controllers and enter ones own swing/strike parameters. 
3. Button presses from recognised but unassigned controllers were producing calls.
I have assumed that any requirement to call from outside the circle can be done using the keyboard so prevented this.

**Comment by lelandpaul** [comment] 2021-03-08 14:15
#214 has been merged — thanks, Mike! I'm closing this issue.

**Closed by lelandpaul** 2021-03-08 14:15 UTC
